In [21]:
#Fundamental imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
#Import csv 
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
#Type of the DataFrame unployment
type(unemployment)

pandas.DataFrame

In [ ]:
#Obtain the first 5 rows
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
#Obtain the size of the DatFrame
unemployment.shape

(20796, 5)

In [ ]:
#Obtain the columns of the DataFrame
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
#Types of the columns 
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
#Summary of the table 
unemployment.describe

<bound method NDFrame.describe of       country seasonality    month  unemployment  unemployment_rate
0          at         nsa  1993.01        171000                4.5
1          at         nsa  1993.02        175000                4.6
2          at         nsa  1993.03        166000                4.4
3          at         nsa  1993.04        157000                4.1
4          at         nsa  1993.05        147000                3.9
...       ...         ...      ...           ...                ...
20791      uk       trend  2010.06       2429000                7.7
20792      uk       trend  2010.07       2422000                7.7
20793      uk       trend  2010.08       2429000                7.7
20794      uk       trend  2010.09       2447000                7.8
20795      uk       trend  2010.10       2455000                7.8

[20796 rows x 5 columns]>

In [ ]:
#Create the list
my_list = ['a','b','c','d','e','f']

In [ ]:
#Explore the last 4 items
#Method 1
my_list[2:]

['c', 'd', 'e', 'f']

In [ ]:
#Explore the last 4 items
#Method 2
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

# countries.csv exploration

In [22]:

country = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv')

In [23]:
country.head()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

In [24]:
country.tail()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617
26,es,ES,eu,Spain,Espagne,Spanien,39.895013,-2.988296
27,se,SE,eu,Sweden,Suède,Schweden,62.198467,14.896307
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795
29,uk,GB,eu,United Kingdom,Royaume-Uni,Vereinigtes Königreich,54.315447,-2.232612

In [25]:
country.shape

(30, 8)

In [26]:
country.info

<bound method DataFrame.info of    country google_country_code country_group  \
0       at                  AT            eu
1       be                  BE            eu
2       bg                  BG            eu
3       hr                  HR        non-eu
4       cy                  CY            eu
5       cz                  CZ            eu
6       dk                  DK            eu
7       ee                  EE            eu
8       fi                  FI            eu
9       fr                  FR            eu
10      de                  DE            eu
11      gr                  GR            eu
12      hu                  HU            eu
13      ie                  IE            eu
14      it                  IT            eu
15      lv                  LV            eu
16      lt                  LT            eu
17      lu                  LU            eu
18      mt                  MT            eu
19      nl                  NL            eu
20      no                  NO        non-eu
21      pl                  PL            eu
22      pt                  PT            eu
23      ro                  RO            eu
24      sk                  SK            eu
25      si                  SI            eu
26      es                  ES            eu
27      se                  SE            eu
28      tr                  TR        non-eu
29      uk                  GB            eu

                                      name_en  \
0                                     Austria
1                                     Belgium
2                                    Bulgaria
3                                     Croatia
4                                      Cyprus
5                              Czech Republic
6                                     Denmark
7                                     Estonia
8                                     Finland
9                                      France
10  Germany (including  former GDR from 1991)
11                                     Greece
12                                    Hungary
13                                    Ireland
14                                      Italy
15                                     Latvia
16                                  Lithuania
17                                 Luxembourg
18                                      Malta
19                                Netherlands
20                                     Norway
21                                     Poland
22                                   Portugal
23                                    Romania
24                                   Slovakia
25                                   Slovenia
26                                      Spain
27                                     Sweden
28                                     Turkey
29                             United Kingdom

                                              name_fr  \
0                                            Autriche
1                                            Belgique
2                                            Bulgarie
3                                             Croatie
4                                              Chypre
5                                  République tchèque
6                                            Danemark
7                                             Estonie
8                                            Finlande
9                                              France
10  Allemagne (incluant l'ancienne RDA à partir de...
11                                              Grèce
12                                            Hongrie
13                                            Irlande
14                                             Italie
15                                           Lettonie
16                                           Lituanie
17                                         Luxembourg
18                                              Malte
19                                           Pays-Bas
20                                            Norvège
21                                            Pologne
22                                           Portugal
23                                           Roumanie
24                                          Slovaquie
25                                           Slovénie
26                                            Espagne
27                                              Suède
28                                            Turquie
29                                        Royaume-Uni

                                              name_de   latitude  longitude
0                                          Österreich  47.696554  13.345980
1                                             Belgien  50.501045   4.476674
2                                           Bulgarien  42.725674  25.482322
3                                            Kroatien  44.746643  15.340844
4                                              Zypern  35.129141  33.428682
5                               Tschechische Republik  49.803531  15.474998
6                                            Dänemark  55.939684   9.516689
7                                             Estland  58.592469  25.806950
8                                            Finnland  64.950159  26.067564
9                                          Frankreich  46.710994   1.718561
10  Deutschland (einschließlich der ehemaligen DDR...  51.163825  10.454048
11                                       Griechenland  39.698467  21.577256
12                                             Ungarn  47.161163  19.504265
13                                             Irland  53.415260  -8.239122
14                                            Italien  42.504191  12.573787
15                                           Lettland  56.880117  24.606555
16                                            Litauen  55.173687  23.943168
17                                          Luxemburg  49.815319   6.133352
18                                              Malta  35.902422  14.447461
19                                        Niederlande  52.108118   5.330198
20                                           Norwegen  64.556460  12.665766
21                                              Polen  51.918907  19.134334
22                                           Portugal  39.558069  -7.844941
23                                           Rumänien  45.942611  24.990152
24                                           Slowakei  48.672644  19.700032
25                                          Slowenien  46.149259  14.986617
26                                            Spanien  39.895013  -2.988296
27                                           Schweden  62.198467  14.896307
28                                             Türkei  38.952942  35.439795
29                             Vereinigtes Königreich  54.315447  -2.232612  >